version: '3.5'
services:
  app:
          build: .
          ports:
                  - "8080:8080"
                  - "8081:80"
                  - "8443:443"

          container_name: ${ENV_APP_CONTAINER_NAME}

          volumes:
                  - finances_cache:/var/www/html/officemgr/writable/cache
                  - finances_debugbar:/var/www/html/officemgr/writable/debugbar
                  - finances_logs:/var/www/html/officemgr/writable/logs
                  - finances_uploads:/var/www/html/officemgr/writable/uploads

          env_file:
            - .env

          networks:
            - frontend_office
            - backend_office

  mariadb:
    image: mariadb
    container_name: ${ENV_DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_DB_ROOT_PASS}
      MYSQL_DATABASE: ${ENV_DB_NAME}
      MYSQL_USER: ${ENV_DB_USER}
      MYSQL_PASSWORD: ${ENV_DB_PASS}

    networks:
      - backend_office
    restart: on-failure

    volumes:
     - database_officemgr:/var/lib/mysql


volumes:
        finances_cache:

        finances_debugbar:

        finances_logs:

        finances_uploads:

        database_officemgr:

networks:
  frontend_office:
    driver: bridge
  backend_office:
    driver: bridge
